2024-04-18T20:12:19.781Z - TypeError: User.create is not a function
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:18:34)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:47:12)
2024-04-18T20:13:22.176Z - Error: Error al crear un nuevo usuario
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:13)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:18:34)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T20:20:11.283Z - Error: Error al crear un nuevo usuario
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:13)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T20:23:03.374Z - Error: Error al crear un nuevo usuario
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:13)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T20:23:24.050Z - Error: Error al crear un nuevo usuario
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:13)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T20:23:25.127Z - Error: Error al crear un nuevo usuario
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:13)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T20:23:39.089Z - Error: Error al crear un nuevo usuario
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:13)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T20:24:46.448Z - Error: Error al crear un nuevo usuario TypeError: db.promise is not a function
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:13)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T20:25:05.292Z - Error: Error al crear un nuevo usuario TypeError: db.promise is not a function
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:13)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T20:25:30.985Z - Error: Error al crear un nuevo usuario TypeError: db.promise is not a function
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:13)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T20:26:19.622Z - Error: Error al crear un nuevo usuario
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:13)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T20:55:09.044Z - TypeError: Cannot read properties of undefined (reading 'query')
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:41)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T21:04:31.423Z - Error: No se ha establecido una conexión a la base de datos
    at getConnection (D:\Programacion\2024\steticapp\steticapp-backend\src\config\dbConfig.js:22:11)
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:8:26)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
2024-04-18T21:05:33.543Z - Error: No se ha establecido una conexión a la base de datos
    at getConnection (D:\Programacion\2024\steticapp\steticapp-backend\src\config\dbConfig.js:22:11)
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:8:26)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
2024-04-18T21:10:37.983Z - Error: No se ha establecido una conexión a la base de datos
    at getConnection (D:\Programacion\2024\steticapp\steticapp-backend\src\config\dbConfig.js:22:11)
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:8:26)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
2024-04-18T22:13:16.353Z - Error: No se ha establecido una conexión a la base de datos
    at getConnection (D:\Programacion\2024\steticapp\steticapp-backend\src\config\dbConfig.js:22:11)
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:8:26)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
2024-04-18T22:15:10.411Z - TypeError: connection.query is not a function
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:45:41)
    at createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\express\lib\router\index.js:175:3)
2024-04-18T23:06:01.326Z - Error: Duplicate entry 'usuario@example.com' for key 'email'
    at PromiseConnection.query (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\mysql2\promise.js:94:22)
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:43:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:22)
2024-04-19T00:43:35.191Z - Error: El nombre de usuario ya está en uso. Por favor, elige otro nombre de usuario.
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:27:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:22)
2024-04-19T00:43:54.770Z - Error: Duplicate entry 'otro@example.com' for key 'email'
    at PromiseConnection.query (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\mysql2\promise.js:94:22)
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:52:41)
    at async createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:22)
2024-04-19T00:57:06.311Z - Error: Duplicate entry 'otro@example.com' for key 'email'
    at PromiseConnection.query (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\mysql2\promise.js:94:22)
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:47:41)
    at async createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:22)
2024-04-19T00:57:13.028Z - Error: Duplicate entry 'ejemplo_usuario' for key 'username'
    at PromiseConnection.query (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\mysql2\promise.js:94:22)
    at Object.createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:47:41)
    at async createUser (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:7:22)
2024-04-19T02:02:39.463Z - Error: Unknown column 'hashedPassword' in 'field list'
    at PromiseConnection.query (D:\Programacion\2024\steticapp\steticapp-backend\node_modules\mysql2\promise.js:94:22)
    at Object.updateUserById (D:\Programacion\2024\steticapp\steticapp-backend\src\models\userModel.js:156:41)
    at async updateUserById (D:\Programacion\2024\steticapp\steticapp-backend\src\controllers\userController.js:39:7)
2024-07-03T21:55:02.233Z - TypeError: Cannot read properties of undefined (reading 'pool')
    at getConnection (D:\Programacion\2024\toribio-webapp\backend\node_modules\mysql2\promise.js:338:27)
    at Object.createUser (D:\Programacion\2024\toribio-webapp\backend\src\models\userModel.js:8:32)
    at createUser (D:\Programacion\2024\toribio-webapp\backend\src\controllers\userController.js:14:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:328:13)
    at D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:346:12)
2024-07-03T21:59:17.407Z - TypeError: getConnection is not a function
    at Object.createUser (D:\Programacion\2024\toribio-webapp\backend\src\models\userModel.js:8:32)
    at createUser (D:\Programacion\2024\toribio-webapp\backend\src\controllers\userController.js:14:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:328:13)
    at D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:280:10)
2024-07-03T21:59:51.247Z - TypeError: pool is not a function
    at Object.createUser (D:\Programacion\2024\toribio-webapp\backend\src\models\userModel.js:8:32)
    at createUser (D:\Programacion\2024\toribio-webapp\backend\src\controllers\userController.js:14:38)
    at Layer.handle [as handle_request] (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:328:13)
    at D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Programacion\2024\toribio-webapp\backend\node_modules\express\lib\router\index.js:280:10)
2024-07-06T16:32:04.912Z - AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
2024-07-06T16:33:56.179Z - AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
2024-07-06T16:46:31.179Z - AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
2024-07-06T16:46:50.500Z - AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
2024-07-06T16:51:13.454Z - AggregateError
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5)
2024-07-27T18:20:36.446Z - Error: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
